### ISSUE TITLE
rust language

### ISSUE THREAD

**Issue by HTML-Enjoyer** [table106/buckshotCS#1]
**Is your feature request related to a problem? Please describe.**
yes problem. i you must use the rust programming language

**Describe the solution you'd like**
a very concise solution: use the rust programing language

**Describe alternatives you've considered**
use the rust programming language.

**Additional context**
rewritting applications in rust often yields very positive results, such as:
 - speed (rust is compiled, so better than c# or python)
 - maintainability

thank for listening
-- html enjoy

**Comment by table106** [comment]
well shit, idk rust
